### ISSUE TITLE
Windows Guide

### ISSUE THREAD

**Issue by waylaa** [auc0le/mine-qubic-amd-zluda-rqiner#1]
Will there be a guide for compiling for Windows?

**Comment by auc0le** [comment]
As I don't own a AMD GPU on a windows box (I tested this on an APU in Linux), no I won't be making a windows guide.  However, I have added this note to the write up:

NOTE: WSL on windows does NOT support pure GPU passthru so ZLUDA will NOT work on Windows WSL. Some user's have reported getting this ZLUDA setup to work in base windows and that is beyond the scope of this document but here is what they said: need to have zluda.exe and the dlls it came with in the same directory as the rqiner and load it through powershell.

Good luck!
