### ISSUE TITLE
Will old AMD GPUs like RX580(GCN4.0) be supported soon?

### ISSUE THREAD

**Issue by TickToTock** [auc0le/mine-qubic-amd-zluda-rqiner#2]
Documents of mine-qubic-amd-zluda-rqiner indicates AMD GPUs newer than RDNA1 RDNA2 architecture is now working via zluda.
Will the older AMD RX 580 GPUs(GCN 4.0) be supported for mining Qubic in the future?

**Comment by auc0le** [comment]
Card compatibility is manged by the Zluda and rocm projects.  The developers of mining apps have no control over this.

Given that the Zluda project is basically dead at this point, I think the answer to your question is "All signs point to no at this time".
